services:
  db:
    image: postgres
    container_name: shop_backend
    ports:
      - "8585:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: testing123
      POSTGRES_USER: testuser
      POSTGRES_DATABASE: testdatabase