spring:
  application:
  name: shop_backend
  datasource:
    image: postgres:18.3
    url: jdbc:postgresql://localhost:8585/testuser
    username: testuser

#    will later be in env, this is for testing purposes
    password: testing123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-database-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: awd891sdawkoie123890dk12312sajwyhawekawei1231sadkeo